/'
 ' * * * Group 36 UML Diagram * * * 
 '
 ' You will need to install PlantUML tools to generate the 
 ' Image from source.
 ' 
 ' https://plantuml.com/download
 '
 ' # : Protected
 ' ~ : Package Private
 ' + : Public
 ' - : Private
'/

@startuml Use_case
left to right direction

actor Student 
actor Admin
actor Conveynor

skinparam ArrowThickness 2
skinparam ArrowColor #black

package OurSystem {
    usecase "Create Course" as create_cse

    usecase "Create accounts" as create_acc
    usecase "Create Student account" as student_acc
    create_acc <. student_acc #blue : << extends >>
    usecase "Create conveynor account" as conveynor_acc
    create_acc <. conveynor_acc #blue : << extends >>

    usecase "Upload learning materials" as upload_learning_materials
    usecase "Daily tasks" as todos
    usecase "View schedule" as view_sched
    usecase "Adjust schedule" as adjustment
    usecase "Dashboard" as dashboard

    /'
     ' Whenever adjustment use case happens, view schedule use case will happen
     ' as a subcase of the adjstment use case. 
     '/
    adjustment .> view_sched #DarkRed : << includes >> 

    create_acc -- Admin

    Student -- view_sched
    Student -- todos
    Student -- adjustment
    Student -- dashboard

    Conveynor -- upload_learning_materials
    Conveynor -- create_cse

    /' 
     ' Whenever a course is created, learning materials should be uploaded.
     '/
    create_cse .> upload_learning_materials #DarkRed : << includes >>
}

@enduml